### ISSUE TITLE
您好，运行报错

### ISSUE THREAD

**Issue by vincicheng** [aidserv/aid#3]
我用的是VS 2022最新版，运行后提示这个是一个无效的WIN32程序，请问怎么处理呢？

**Comment by zhoujunhe** [comment]
你有能力，可以把他升级到 VS 2022 版本编译，然后拉起 pull request

**Comment by vincicheng** [comment]
这个我没操作过，请问下，是不是我用2019版可以编译通过？

**Comment by zhoujunhe** [comment]
> 这个我没操作过，请问下，是不是我用2019版可以编译通过？

已经 Releases v1.0.0-beta 版本了，你直接使用 aid.dll 来调用函数好了
