### ISSUE TITLE
如何联系

### ISSUE THREAD

**Issue by Rex-fei** [aidserv/aid#5]
你好，我们现在有这方面的需求，想问一下，如何联系你，帮我们解决一些问题。可付费

**Comment by zhoujunhe** [comment]
qq  31722980

**Comment by Rex-fei** [comment]
> QQ 31722980

已经添加 麻烦通过一下

**Comment by flashfoxter** [comment]
> qq 31722980

Can you share WeChat ?

**Comment by zhoujunhe** [comment]
qq

**Comment by zhoujunhe** [comment]
> > QQ 31722980
> 
> 你能分享微信吗？

qq

**Comment by Diarly** [comment]
有个问题请教下，加你qq了，同意一下
