### ISSUE TITLE
服务器端运行/部署

### ISSUE THREAD

**Issue by SoY0ung** [aidserv/aid#8]
您好，请问Server端要怎么部署，需要用到哪些函数呢？
运行时发现您的Server端好像停用了，什么时候恢复呢？
希望您能提供联系方式，想请教下您，谢谢！

**Comment by zhoujunhe** [comment]
已经[Releases](https://github.com/zhoujunhe/aid/releases)出版本了，你可以直接下载解压，以管理员运行 cmd 命令行提示符，使用cpp  就可以正确授权，然后用ideviceinstaller -i huaji1.0.24.ipa  安装换机助手来测试授权是否成功，服务端比较复杂，qq:31722980,可以QQ里聊。客户端我还在简化中。

**Comment by xanadu-lee** [comment]
@SoY0ung 
https://github.com/iOS-Auth/iOSAuthRuntime
这里有开源版本
